### ISSUE TITLE
Qidi Connections popup window not coming up

### ISSUE THREAD

**Issue by 3dprintedmac** [alkaes/QidiPrint#1]
I've dropped and extracted the zip files into the indicated places. i've triple checked i put them in the right places and the format looks the same as other extensions and plugins. I open cura and see the Qidiprint selection with QidiConnections, but when i click on it, nothing happens. Any help or ideas to double check would be appreciated, thanks!

**Comment by alkaes** [comment]
What cura version do you have?
Post your `%USERPROFILE%\AppData\Roaming\cura\stderr.log`

**Comment by 3dprintedmac** [comment]
Just upgraded to 4.7.1 before trying to load the plugin. and i'm not seeing a file named that in the folder....

**Comment by alkaes** [comment]
This file is created by Cura automatically at each run. 
Run Cura try to click on QidiConnections and then see if any errors related to QidiPrint plugin are posted inside this file

**Comment by 3dprintedmac** [comment]
I'm seeing this in a file labeled "cura" that seems to be logging all program stuff. This is a section that seems about the plugin. thanks for the help! 
![troubleshooting qidi plugin](https://user-images.githubusercontent.com/71304680/94350736-c6d41380-0016-11eb-8b92-877fc7818b2c.PNG)

**Comment by alkaes** [comment]
Maybe there is conflict with some other plugins, please attach the whole log as a text file

**Comment by 3dprintedmac** [comment]
[cura 9-26.txt](https://github.com/alkaes/QidiPrint/files/5287536/cura.9-26.txt)
Thanks for looking into it for me! That would make sense about another plugin potentially conflicting.

**Comment by alkaes** [comment]
Looks like some of the plugin files are missing:
![image](https://user-images.githubusercontent.com/41850898/94360548-c25f3780-00b6-11eb-9bdd-97beca7edf74.png)
Also there are a lot of other errors in deserialization of container ID.
My advice is to remove the %USERPROFILE%\AppData\Roaming\cura folder an to
install all plugins from the beginning

**Comment by alkaes** [comment]
It appears that this file was missing inside the QidiPrint-1.1.0.zip. Now fixed

**Comment by 3dprintedmac** [comment]
Thank you! Got it working based on the information you provided by pulling the file from the past version in. 

It’s been working great now! I appreciate the work you put in to make things SO much more convenient for everyone 

-nate
