### ISSUE TITLE
"Save to File" does not include the QIDI code

### ISSUE THREAD

**Issue by damy2000** [alkaes/QidiPrint#4]
Congratulations on the wonderful work you have done!

One useful feature that is missing or maybe it's a bug, is when the "Save to File" file is saved the file does not include the GCODE for preview and time (M4010, M2100).

It could be implemented with another button eg: "Save to QIDI file" or integrated directly into "Save to File".

Thanks for your attention !

Damiano Trisciani

**Comment by PM-John** [comment]
@damy2000 
I had the same problem. You will need to dump the Qidi Printer Files into the Cura folder of the printer
Do this step that I got from the code section. also use Cura 4.8

If you don't have Qidi printers available in Cura, unpack the [Qidi Printer Definitions.zip](https://github.com/alkaes/QidiPrint/releases/download/1.2.0/Qidi.Printer.Definitions.zip) to this specific folder:

Windows: %USERPROFILE%\AppData\Roaming\cura\4.8\
MacOS: ~/Library/Application Support/Cura/4.8/
Linux: /home/<username>/.local/share/cura/4.8/

once you copy the files, add the new printer and it should work.

**Comment by damy2000** [comment]
I solved by installing the CURA plugin ChituCodeWriter https://github.com/Spanni26/ChituCodeWriter ! 
I've seen is also used in this plugin, but probably not integrated into the "Save to File" menu, and it is not the default choice.
