### ISSUE TITLE
Qidi Printer Definitions fixes

### ISSUE THREAD

**Issue by volgy** [alkaes/QidiPrint#8]
The original Qidi Printer Definitions have some strong overrides. Because these are placed in the _user profile_ folder these values will have priority over the default Cura definitions (so the situation is a bit different than with Qidi-Print). 
This is especially problematic with the temperature settings (selecting different materials in Cura will not change the printing temperature). Removing at least the following properties from `definitions/qidi.def.json` resolve this issue:

~~"material_print_temperature":{ "value": 200 }~~
~~"material_bed_temperature":{ "default_value": 50 }~~
~~"default_material_print_temperature":{ "value": 200 }~~

In general, it would be useful to keep a curated/maintained version of the definition files in this or another GitHub repo.
Thank you for your work on QidiPrint! Without this plug-in, I would have bought a different printer.

**Comment by alkaes** [comment]
Thank you for your feedback,
Issue fixed, with other improvments in the new dedicated repo:
[https://github.com/alkaes/Qidi-Printer-Definitions](url)

**Comment by volgy** [comment]
Great! Thanks!
